version: '3'
services:
  scrapper:
    container_name: "scrapper"
    build: "scrapper"
    environment:
     - NODE_ENV=production
  # scrapper-db:
  #   container_name: "data-db"
  #   build: "data-db"
  #   port:
  #     - "8080:6379"
  # analyzer:
  #   container_name: "analyzer"
  #   build: "analyzer"
  # analyzer-db:
  #   container_name: "analyzer-db"
  #   build: "analyzer-db"
  #   port:
  #     - "8081:6379"
  # api:
  #   container_name: "api"
  #   build: "api"
  #   port:
  #     - "8082:80"
  # api-facade:
  #   container_name: "api-facade"
  #   build: "api-facade"
  #   port:
  #     - "8083:80"
  # front-end:
  #   container_name: "front-end"
  #   build: "front-end"
  #   port:
  #     - "8084:80"
